resources:
  - ../../base
images:
  - name: <registry>/mc-api
    newName: ghcr.io/${REPO}/mc-api
    newTag: latest
  - name: <registry>/mc-web
    newName: ghcr.io/${REPO}/mc-web
    newTag: latest


